
[package]
name = "bitcoin"
version = "0.0.1"
authors = ["Andrew Poelstra <apoelstra@wpsoftware.net>"]

[lib]
name = "bitcoin"
path = "src/lib.rs"

[dependencies.secp256k1]
git = "https://github.com/apoelstra/rust-secp256k1.git"

[dependencies.eventual]
git = "https://github.com/carllerche/eventual"

[dependencies]
byteorder = "*"
num = "*"
num_cpus = "*"
rand = "*"
rust-crypto = "*"
rustc-serialize = "*"
serde = "*"
serde_macros = "*"
time = "*"

