
[package]
name = "bitcoin"
version = "0.0.1"
authors = ["Andrew Poelstra <apoelstra@wpsoftware.net>"]

[lib]
name = "bitcoin"
path = "src/lib.rs"

[dependencies.secp256k1]
git = "https://github.com/apoelstra/bitcoin-secp256k1-rs.git"

[dependencies]
byteorder = "*"
rand = "*"
rust-crypto = "*"
rustc-serialize = "*"
time = "*"

